;(function ($, window, undefined) {
    var dataSet = [
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-posted'>Posted</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-open'>Open</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-void'>Void</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-bank'>Bank</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
        [ "1","<a href='javascript:;'>AMRD201706-0027</a>","<div class='row'><a class='col-12' href='javascript:;'>MICHAEL ALPHONSUS</a></div><div class='row'><div class='col-3 info-title'>Creator</div><div class='col-7 info-content'>XUEFEN</div><div class='col-3 info-title'>Description</div><div class='col-7 info-content'>FBD7322E-001 : 006~006 IN</div><div class='col-3 info-title'>Bank Acc</div><div class='col-7 info-content'>111600 --- AM - DAILY COLLECTION</div></div>", "08/09/2017","<a href='javascript:;' class='amount'>CASH</a>","<a href='javascript:;' class='amount'>18,000.00</a>","<button class='btn btn-delete'>Close</button>", "<i class='fa fa-ellipsis-v fa-2x pull-right'></i><i class='fa fa-print fa-2x pull-right'></i>"],
    ];
    $(document).ready(function () {        
        var monitor=$('#entry-list').DataTable( {
            data: dataSet,
            "iDisplayLength": 10,
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": false,
            "info": false,
            columns: [
                { title: "No" },
                { title: "RV No" },
                { title: "Company Name" },
                { title: "Period Date" },
                { title: "Cheque / Cash" },
                { title: "Total Amount" },
                { title: "Status" },
                { title: "" }
            ]
        });
        /*************************/
        $( "#mount-range" ).slider({
            range: true,
            min: 0,
            max: 9999999.99,
            step: 0.01,
            values: [0,4545939.32 ],
            slide: function( event, ui ) {
                $( "#from" ).val(ui.values[0]);
                $( "#to" ).val(ui.values[1] );
            }
        });
        /**************************/
        $(document).on('click','.btn-save',function(){
            $('[data-toggle="popover"]').popover('hide');
        })
        $(document).on('click','.btn-cancel',function(){
            $('[data-toggle="popover"]').popover('hide');
        })
        $(document).on('show.bs.popover','[data-toggle="popover"]',function () {
          $('[data-toggle="popover"]').not(this).popover('hide');
        })
    });
})(jQuery, window);