;(function ($, window, undefined) {
    var dataSet = [
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/office.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='not-active'><i class='fa fa-close'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/office.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user4-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user4-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user4-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user4-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user3-128x128.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"],
        ["<div class='row'><div class='col-2 text-center'><div class='checkbox'><input type='checkbox'><label></label></div><div style='background:url(img/user2-160x160.jpg);' class='user-avatar'/><span class='active'><i class='fa fa-check'></i></span></div></div><div class='col-9'><div class='row name'><div class='col-12'>A-COST-COMM</div></div><div class='row priority'><div class='col-12'>Priority: <b class='priority'>account_2</b></div></div><div class='row worked-time'><div class='col-4'><div>(ALT) Monday ~ Friday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Saturday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div><div class='col-3'><div>(ALT) Sunday</div><div class='time-col'>From <div>20:15</div></div><div class='time-col'>To <div>20:15</div></div></div></div></div></div>","<i class='fa fa-ellipsis-v fa-2x pull-right'></i>"]
    ];
    $(document).ready(function () {        
        var monitor=$('#stafflogin-list').DataTable( {
            data: dataSet,
            "iDisplayLength": 10,
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": false,
            "info": false,
            columns: [
                { title: "<div class='checkbox'><input type='checkbox' class='check-all'><label></label></div> <h3 class='card-title'>ID Login <small>ALT - Allow Login Time</small></h3>" },
                { title: "<button class='btn pull-right btn-clean'><i class='fa fa-trash'></i> clear</button>" }
            ]
        });
        /*************************/
        $( "#mount-range" ).slider({
            range: true,
            min: 0,
            max: 9999999.99,
            step: 0.01,
            values: [0,4545939.32 ],
            slide: function( event, ui ) {
                $( "#from" ).val(ui.values[0]);
                $( "#to" ).val(ui.values[1] );
            }
        });
        /**************************/
        $(document).on('click','.btn-save',function(){
            $('[data-toggle="popover"]').popover('hide');
        })
        $(document).on('click','.btn-cancel',function(){
            $('[data-toggle="popover"]').popover('hide');
        })
        $(document).on('show.bs.popover','[data-toggle="popover"]',function () {
          $('[data-toggle="popover"]').not(this).popover('hide');
        })
        $(document).on('click','.check-all',function () {
            var _checkbox=$('#stafflogin-list').find("input[type='checkbox']").not(this);
            if($(this).prop('checked')==true){
                _checkbox.attr("checked",true);
            }else{
                _checkbox.attr("checked",false);
            }
        })
    });
})(jQuery, window);